apiVersion: v2
name: gloo
description: Feature-filled edge proxy to handle disparate services in the cluster.
version: 1.0.2
dependencies:
    - name: gloo
      version: 1.11.6
      repository: https://storage.googleapis.com/solo-public-helm